import Head from 'next/head'
import { client } from '../shopifyClient'
import Product from '../components/Product'

export const getStaticProps = async () => {
  const products = await client.product.fetchAll()

  return {
    props: {
      products: JSON.parse(JSON.stringify(products))
    }
  }
}

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Cupcakes</h1>
        <ul>
          {products.map(product => (
            <Product key={product.id} product={product} />
          ))}
        </ul>
      </main>
    </>
  )
}
